export const COMMUNITIES = [
  {
    id: "vikings",
    name: "Vikings Fans",
    region: "Twin Cities",
    members: 1284,
    activity: "12 events this weekend",
    color: "bg-primary",
    description: "Sundays, Skol chants, and stadium energy.",
  },
  {
    id: "twins",
    name: "Twins Fans",
    region: "Twin Cities",
    members: 942,
    activity: "Game night Friday",
    color: "bg-coral",
    description: "Target Field regulars and dollar dog die-hards.",
  },
  {
    id: "wild",
    name: "Wild Hockey",
    region: "Twin Cities",
    members: 612,
    activity: "New conversation today",
    color: "bg-forest",
    description: "Puck drops, watch parties, and rec league chat.",
  },
  {
    id: "family",
    name: "Family Adventures",
    region: "Eagan",
    members: 388,
    activity: "4 playdates this week",
    color: "bg-sage",
    description: "Parents who'd rather not spend Saturday at home.",
  },
  {
    id: "outdoor",
    name: "Outdoor & Trails",
    region: "Twin Cities",
    members: 521,
    activity: "Trail run Saturday",
    color: "bg-secondary",
    description: "Trails, climbs, lakes, and long Saturday mornings.",
  },
  {
    id: "food",
    name: "Food & Drink",
    region: "Twin Cities",
    members: 734,
    activity: "Trivia night Thursday",
    color: "bg-primary",
    description: "New spots, neighborhood gems, and patio season.",
  },
  {
    id: "pickup",
    name: "Weekend Pickup Sports",
    region: "Twin Cities",
    members: 264,
    activity: "Soccer at 6pm",
    color: "bg-coral",
    description: "Soccer, basketball, frisbee — whoever shows up.",
  },
];

export const EVENTS = [
  {
    id: "vikes",
    name: "Vikings vs Packers tailgate",
    communityId: "vikings",
    community: "Vikings Fans",
    location: "US Bank Stadium · Lot C",
    address: "401 Chicago Ave, Minneapolis, MN",
    when: "Sun · 1:00pm",
    going: 47,
    avatars: ["JM", "SA", "RT", "KP", "BN", "EW"],
    live: true,
    description:
      "Pulling up early to Lot C around 10. Blue tent, brats on the grill, bring a chair. Heading in together around 12:30.",
    host: { name: "Sam A.", initials: "SA" },
  },
  {
    id: "trail",
    name: "Saturday trail run",
    communityId: "outdoor",
    community: "Outdoor & Trails",
    location: "Lebanon Hills · Eagan",
    address: "860 Cliff Rd, Eagan, MN",
    when: "Sat · 8:00am",
    going: 12,
    avatars: ["EB", "NL", "TC", "MR"],
    description: "Easy 6 miles, coffee after at the trailhead. All paces welcome.",
    host: { name: "Erin B.", initials: "EB" },
  },
  {
    id: "park",
    name: "Kids + coffee at the park",
    communityId: "family",
    community: "Family Adventures",
    location: "Como Regional Park",
    address: "1199 Midway Pkwy, St Paul, MN",
    when: "Sat · 10:00am",
    going: 8,
    avatars: ["MR", "DH", "AS"],
    description: "Meet at the big playground. Bringing donuts and a thermos.",
    host: { name: "Maya R.", initials: "MR" },
  },
  {
    id: "trivia",
    name: "Trivia night @ Surly",
    communityId: "food",
    community: "Food & Drink",
    location: "Surly Brewing · Mpls",
    address: "520 Malcolm Ave SE, Minneapolis, MN",
    when: "Thu · 7:00pm",
    going: 19,
    avatars: ["BL", "VK", "JN", "CR"],
    description: "Teams of 4-6. Grabbing the big booth in back. We're 'The Hot Dish'.",
    host: { name: "Ben L.", initials: "BL" },
  },
  {
    id: "farm",
    name: "Mill City Farmers Market",
    communityId: "food",
    community: "Food & Drink",
    location: "Mill City · Mpls",
    address: "704 S 2nd St, Minneapolis, MN",
    when: "Sat · 9:00am",
    going: 6,
    avatars: ["GH", "PT"],
    description: "Slow walk through the market, then coffee at Spyhouse.",
    host: { name: "Grace H.", initials: "GH" },
  },
];

export const AVATAR_PALETTE = [
  "bg-primary/85 text-primary-foreground",
  "bg-sage/85 text-white",
  "bg-coral/85 text-white",
  "bg-forest/85 text-white",
  "bg-accent text-accent-foreground",
];
