/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppGroupsRouteImport } from './routes/_app/groups'
import { Route as AppProfileUserIdRouteImport } from './routes/_app/profile.$userId'
import { Route as AppGroupGroupIdRouteImport } from './routes/_app/group.$groupId'
import { Route as AppActivityActivitySlugRouteImport } from './routes/_app/activity.$activitySlug'
import { Route as AppGroupGroupIdScheduleRouteImport } from './routes/_app/group.$groupId.schedule'
import { Route as AppGroupGroupIdChatRouteImport } from './routes/_app/group.$groupId.chat'
import { Route as AppActivityActivitySlugProfileRouteImport } from './routes/_app/activity.$activitySlug.profile'
import { Route as AppGroupGroupIdThreadThreadIdRouteImport } from './routes/_app/group.$groupId.thread.$threadId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppGroupGroupIdRoute = AppGroupGroupIdRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityActivitySlugRoute = AppActivityActivitySlugRouteImport.update({
  id: '/activity/$activitySlug',
  path: '/activity/$activitySlug',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupGroupIdScheduleRoute = AppGroupGroupIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppGroupGroupIdRoute,
} as any)
const AppGroupGroupIdChatRoute = AppGroupGroupIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppGroupGroupIdRoute,
} as any)
const AppActivityActivitySlugProfileRoute =
  AppActivityActivitySlugProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AppActivityActivitySlugRoute,
  } as any)
const AppGroupGroupIdThreadThreadIdRoute =
  AppGroupGroupIdThreadThreadIdRouteImport.update({
    id: '/thread/$threadId',
    path: '/thread/$threadId',
    getParentRoute: () => AppGroupGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/groups': typeof AppGroupsRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/activity/$activitySlug': typeof AppActivityActivitySlugRouteWithChildren
  '/group/$groupId': typeof AppGroupGroupIdRouteWithChildren
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/activity/$activitySlug/profile': typeof AppActivityActivitySlugProfileRoute
  '/group/$groupId/chat': typeof AppGroupGroupIdChatRoute
  '/group/$groupId/schedule': typeof AppGroupGroupIdScheduleRoute
  '/group/$groupId/thread/$threadId': typeof AppGroupGroupIdThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/groups': typeof AppGroupsRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/activity/$activitySlug': typeof AppActivityActivitySlugRouteWithChildren
  '/group/$groupId': typeof AppGroupGroupIdRouteWithChildren
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/activity/$activitySlug/profile': typeof AppActivityActivitySlugProfileRoute
  '/group/$groupId/chat': typeof AppGroupGroupIdChatRoute
  '/group/$groupId/schedule': typeof AppGroupGroupIdScheduleRoute
  '/group/$groupId/thread/$threadId': typeof AppGroupGroupIdThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/activity/$activitySlug': typeof AppActivityActivitySlugRouteWithChildren
  '/_app/group/$groupId': typeof AppGroupGroupIdRouteWithChildren
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
  '/_app/activity/$activitySlug/profile': typeof AppActivityActivitySlugProfileRoute
  '/_app/group/$groupId/chat': typeof AppGroupGroupIdChatRoute
  '/_app/group/$groupId/schedule': typeof AppGroupGroupIdScheduleRoute
  '/_app/group/$groupId/thread/$threadId': typeof AppGroupGroupIdThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/groups'
    | '/home'
    | '/profile'
    | '/settings'
    | '/activity/$activitySlug'
    | '/group/$groupId'
    | '/profile/$userId'
    | '/activity/$activitySlug/profile'
    | '/group/$groupId/chat'
    | '/group/$groupId/schedule'
    | '/group/$groupId/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/groups'
    | '/home'
    | '/profile'
    | '/settings'
    | '/activity/$activitySlug'
    | '/group/$groupId'
    | '/profile/$userId'
    | '/activity/$activitySlug/profile'
    | '/group/$groupId/chat'
    | '/group/$groupId/schedule'
    | '/group/$groupId/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/groups'
    | '/_app/home'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/activity/$activitySlug'
    | '/_app/group/$groupId'
    | '/_app/profile/$userId'
    | '/_app/activity/$activitySlug/profile'
    | '/_app/group/$groupId/chat'
    | '/_app/group/$groupId/schedule'
    | '/_app/group/$groupId/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/group/$groupId': {
      id: '/_app/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof AppGroupGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity/$activitySlug': {
      id: '/_app/activity/$activitySlug'
      path: '/activity/$activitySlug'
      fullPath: '/activity/$activitySlug'
      preLoaderRoute: typeof AppActivityActivitySlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/group/$groupId/schedule': {
      id: '/_app/group/$groupId/schedule'
      path: '/schedule'
      fullPath: '/group/$groupId/schedule'
      preLoaderRoute: typeof AppGroupGroupIdScheduleRouteImport
      parentRoute: typeof AppGroupGroupIdRoute
    }
    '/_app/group/$groupId/chat': {
      id: '/_app/group/$groupId/chat'
      path: '/chat'
      fullPath: '/group/$groupId/chat'
      preLoaderRoute: typeof AppGroupGroupIdChatRouteImport
      parentRoute: typeof AppGroupGroupIdRoute
    }
    '/_app/activity/$activitySlug/profile': {
      id: '/_app/activity/$activitySlug/profile'
      path: '/profile'
      fullPath: '/activity/$activitySlug/profile'
      preLoaderRoute: typeof AppActivityActivitySlugProfileRouteImport
      parentRoute: typeof AppActivityActivitySlugRoute
    }
    '/_app/group/$groupId/thread/$threadId': {
      id: '/_app/group/$groupId/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/group/$groupId/thread/$threadId'
      preLoaderRoute: typeof AppGroupGroupIdThreadThreadIdRouteImport
      parentRoute: typeof AppGroupGroupIdRoute
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileUserIdRoute: AppProfileUserIdRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppActivityActivitySlugRouteChildren {
  AppActivityActivitySlugProfileRoute: typeof AppActivityActivitySlugProfileRoute
}

const AppActivityActivitySlugRouteChildren: AppActivityActivitySlugRouteChildren =
  {
    AppActivityActivitySlugProfileRoute: AppActivityActivitySlugProfileRoute,
  }

const AppActivityActivitySlugRouteWithChildren =
  AppActivityActivitySlugRoute._addFileChildren(
    AppActivityActivitySlugRouteChildren,
  )

interface AppGroupGroupIdRouteChildren {
  AppGroupGroupIdChatRoute: typeof AppGroupGroupIdChatRoute
  AppGroupGroupIdScheduleRoute: typeof AppGroupGroupIdScheduleRoute
  AppGroupGroupIdThreadThreadIdRoute: typeof AppGroupGroupIdThreadThreadIdRoute
}

const AppGroupGroupIdRouteChildren: AppGroupGroupIdRouteChildren = {
  AppGroupGroupIdChatRoute: AppGroupGroupIdChatRoute,
  AppGroupGroupIdScheduleRoute: AppGroupGroupIdScheduleRoute,
  AppGroupGroupIdThreadThreadIdRoute: AppGroupGroupIdThreadThreadIdRoute,
}

const AppGroupGroupIdRouteWithChildren = AppGroupGroupIdRoute._addFileChildren(
  AppGroupGroupIdRouteChildren,
)

interface AppRouteChildren {
  AppGroupsRoute: typeof AppGroupsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppActivityActivitySlugRoute: typeof AppActivityActivitySlugRouteWithChildren
  AppGroupGroupIdRoute: typeof AppGroupGroupIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppGroupsRoute: AppGroupsRoute,
  AppHomeRoute: AppHomeRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppActivityActivitySlugRoute: AppActivityActivitySlugRouteWithChildren,
  AppGroupGroupIdRoute: AppGroupGroupIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
